ALTER TABLE rooms
  ADD COLUMN IF NOT EXISTS subtitle text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS host_name text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS theme_preset text NOT NULL DEFAULT 'emerald',
  ADD COLUMN IF NOT EXISTS accent_color text NOT NULL DEFAULT '#059669';
